format_version: 2
pipelines:
  instascan:
    group: PyFarm
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      instascan:
        git: git@github.com:biqmind/instascan.git
        blacklist:
          - "*.md"
    stages:
      - build:
          clean_workspace: true
          jobs:
            build:
              tasks:
                - exec:
                    run_if: passed
                    command: yarn
                - exec:
                    run_if: passed
                    command: yarn
                    arguments:
                      - build
      - CNPMPublishJob:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            CNPMPublish:
              resources:
                - rhel-agent
              tasks:
                - exec:
                    run_if: passed
                    command: cnpm
                    arguments:
                      - publish

