format_version: 2
pipelines:
  instascan:
    group: PyFarm
    label_template: ${COUNT}
    lock_behavior: none
    environment_variables:
      NODE_ENV: development
      NPM_CONFIG_STRICT_SSL: false
    materials:
      instascan:
        git: git@github.com:biqmind/instascan.git
        blacklist:
          - "*.md"
    stages:
      - BuildAndPublish:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            build:
              resources:
                - rhel-agent
              tasks:
                - exec:
                    run_if: passed
                    command: yarn
                    arguments:
                      - install
                - exec:
                    run_if: passed
                    command: yarn
                    arguments:
                      - build
                - exec:
                    run_if: passed
                    command: rm
                    arguments:
                      - -rf
                      - src
                - exec:
                    run_if: passed
                    command: bash
                    arguments:
                      - -c
                      - cnpm publish
