format_version: 2
pipelines:
  instascan:
    group: PyFarm
    label_template: ${COUNT}
    lock_behavior: none
    environment_variables:
      NODE_ENV: development
      NPM_CONFIG_REGISTRY: https://cnpm.oc.lanternedge.com/
      NPM_CONFIG_STRICT_SSL: false
    secure_variables:
      REGISTRY_NPMRC: AES:ymTDf5A2C+dL65qw9M8Qhg==:Adb8JhpYLjtDEDAVua26vtpqDH4aqpiOWc4fAtrznpcv5tMyR2qffiq5LoFsGGZv5FwHOLw8FpknSO4j+03jkC+3Po6aLx+ee0QQyhgUUCTDnXq9TFr6BJbLAj9peyzt3IFBuDFhTtvHtd0esU4IJVwFlTsYo5K6nybmkuhW1gqJqVZlhrwZAompsJV+nkwZI30hx4fTViz9qAjcGF9GYM8VCFzI+H0sisCRiNBfzl+qk6uh2/pP4gBz9neU6/Mgw5E/0WoiMaSut48SJNtviCqq01GTbKwqdHBD7fOW0Ne07JftA6rw9a1jNBE5rFBjAJGOWCeXRwSlpWl+jt9WkToFmaRignO/DFEv333+/9/x3UDJD+Wkz3OKsWChYPFIyyE9EzsFy9Vuc2cRpJDMf5FUJi4grQdQhGZNfN0OS3LPJ9P8SomuqJNL12zM7LNAKqquDEoTkUvcviqhx8rvsmvLWAY/T3hrxmWKI+maAjIMXiAKVMKnUMuKrYB5Yf4DpdbOqAPtxCBVAVO2o+cWCBhas3r9CMnrlpT1MuVrfjU=
    materials:
      instascan:
        git: git@github.com:biqmind/instascan.git
        blacklist:
          - "*.md"
    stages:
      - BuildAndPublish:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            build:
              resources:
                - rhel-agent
              tasks:
                - exec:
                    run_if: passed
                    command: yarn
                    arguments:
                      - install
                - exec:
                    run_if: passed
                    command: yarn
                    arguments:
                      - build
                - exec:
                    run_if: passed
                    command: rm
                    arguments:
                      - -rf
                      - src
                - exec:
                    run_if: passed
                    command: bash
                    arguments:
                      - -c
                      - echo -e $(echo "${REGISTRY_NPMRC}") > ~/.npmrc
                - exec:
                    run_if: passed
                    command: bash
                    arguments:
                      - -c
                      - npm publish --registry ${NPM_CONFIG_REGISTRY}
